"""add app_user table and engagement.owner_user_id

§7.4 で確定した Row-Level Security によるテナント分離は新規テナント
スコープ付きテーブルには自動で付かない。app_user にこのマイグレーション
自身で ENABLE/FORCE RLS + POLICY を張る。

Revision ID: 07bcc768b039
Revises: 19e9aacd74dd
Create Date: 2026-08-13 22:32:06.184124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07bcc768b039'
down_revision: Union[str, Sequence[str], None] = '19e9aacd74dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_RLS_TABLES = ["app_user"]
_RLS_POLICY_EXPR = (
    "tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid"
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('function', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('authority', sa.String(length=20), nullable=False),
    sa.Column('sales_group_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['sales_group_id'], ['sales_group.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_user_email'), 'app_user', ['email'], unique=False)
    op.create_index(op.f('ix_app_user_sales_group_id'), 'app_user', ['sales_group_id'], unique=False)
    op.create_index(op.f('ix_app_user_tenant_id'), 'app_user', ['tenant_id'], unique=False)
    op.add_column('engagement', sa.Column('owner_user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_engagement_owner_user_id'), 'engagement', ['owner_user_id'], unique=False)
    op.create_foreign_key(
        'fk_engagement_owner_user_id', 'engagement', 'app_user',
        ['owner_user_id'], ['id'], ondelete='SET NULL',
    )
    # ### end Alembic commands ###

    for table in _RLS_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY tenant_isolation ON {table} "
            f"USING ({_RLS_POLICY_EXPR}) WITH CHECK ({_RLS_POLICY_EXPR})"
        )


def downgrade() -> None:
    """Downgrade schema."""
    for table in reversed(_RLS_TABLES):
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
        op.execute(f"ALTER TABLE {table} NO FORCE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_engagement_owner_user_id', 'engagement', type_='foreignkey')
    op.drop_index(op.f('ix_engagement_owner_user_id'), table_name='engagement')
    op.drop_column('engagement', 'owner_user_id')
    op.drop_index(op.f('ix_app_user_tenant_id'), table_name='app_user')
    op.drop_index(op.f('ix_app_user_sales_group_id'), table_name='app_user')
    op.drop_index(op.f('ix_app_user_email'), table_name='app_user')
    op.drop_table('app_user')
    # ### end Alembic commands ###
