"""add outbox_message and webhook_event tables

§7.4 で確定した Row-Level Security によるテナント分離は新規テナント
スコープ付きテーブルには自動で付かない。outbox_message / webhook_event に
このマイグレーション自身で ENABLE/FORCE RLS + POLICY を張る
(weekly_review / report_snapshot と同じ形。CRM_連携引き継ぎ書.md §9.3)。

Revision ID: 0943c90da570
Revises: 4fbd42e00887
Create Date: 2026-08-15 09:33:39.104965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0943c90da570'
down_revision: Union[str, Sequence[str], None] = '4fbd42e00887'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_RLS_TABLES = ["outbox_message", "webhook_event"]
_RLS_POLICY_EXPR = (
    "tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid"
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox_message',
    sa.Column('target_system', sa.String(length=16), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('ref_type', sa.String(length=32), nullable=True),
    sa.Column('ref_id', sa.String(length=64), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('written_by', sa.String(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbox_message_kind'), 'outbox_message', ['kind'], unique=False)
    op.create_index(op.f('ix_outbox_message_next_attempt_at'), 'outbox_message', ['next_attempt_at'], unique=False)
    op.create_index(op.f('ix_outbox_message_status'), 'outbox_message', ['status'], unique=False)
    op.create_index(op.f('ix_outbox_message_tenant_id'), 'outbox_message', ['tenant_id'], unique=False)
    op.create_table('webhook_event',
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('source_system', sa.String(length=16), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('written_by', sa.String(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'event_id', name='uq_webhook_event_tenant_event_id')
    )
    op.create_index(op.f('ix_webhook_event_event_id'), 'webhook_event', ['event_id'], unique=False)
    op.create_index(op.f('ix_webhook_event_tenant_id'), 'webhook_event', ['tenant_id'], unique=False)
    # ### end Alembic commands ###

    for table in _RLS_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY tenant_isolation ON {table} "
            f"USING ({_RLS_POLICY_EXPR}) WITH CHECK ({_RLS_POLICY_EXPR})"
        )


def downgrade() -> None:
    """Downgrade schema."""
    for table in reversed(_RLS_TABLES):
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
        op.execute(f"ALTER TABLE {table} NO FORCE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_event_tenant_id'), table_name='webhook_event')
    op.drop_index(op.f('ix_webhook_event_event_id'), table_name='webhook_event')
    op.drop_table('webhook_event')
    op.drop_index(op.f('ix_outbox_message_tenant_id'), table_name='outbox_message')
    op.drop_index(op.f('ix_outbox_message_status'), table_name='outbox_message')
    op.drop_index(op.f('ix_outbox_message_next_attempt_at'), table_name='outbox_message')
    op.drop_index(op.f('ix_outbox_message_kind'), table_name='outbox_message')
    op.drop_table('outbox_message')
    # ### end Alembic commands ###
