"""add sales_group, account/engagement/contract hierarchy fields

§7.4 で確定した Row-Level Security によるテナント分離は新規テナント
スコープ付きテーブルには自動で付かない。sales_group にこのマイグレー
ション自身で ENABLE/FORCE RLS + POLICY を張る(account/engagement/
contract は既存マイグレーションでRLS対応済みのため列追加のみで良い)。

Revision ID: 19e9aacd74dd
Revises: d987c93b4b20
Create Date: 2026-08-13 21:14:26.087023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19e9aacd74dd'
down_revision: Union[str, Sequence[str], None] = 'd987c93b4b20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_RLS_TABLES = ["sales_group"]
_RLS_POLICY_EXPR = (
    "tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid"
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_group',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('parent_group_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['parent_group_id'], ['sales_group.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_group_parent_group_id'), 'sales_group', ['parent_group_id'], unique=False)
    op.create_index(op.f('ix_sales_group_tenant_id'), 'sales_group', ['tenant_id'], unique=False)
    op.add_column('account', sa.Column('parent_account_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_account_parent_account_id'), 'account', ['parent_account_id'], unique=False)
    op.create_foreign_key(
        'fk_account_parent_account_id', 'account', 'account',
        ['parent_account_id'], ['id'], ondelete='SET NULL',
    )
    op.add_column('contract', sa.Column('external_system', sa.String(length=32), nullable=True))
    op.add_column('contract', sa.Column('external_id', sa.String(length=128), nullable=True))
    op.add_column('contract', sa.Column('realized_amount', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('engagement', sa.Column('sales_group_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_engagement_sales_group_id'), 'engagement', ['sales_group_id'], unique=False)
    op.create_foreign_key(
        'fk_engagement_sales_group_id', 'engagement', 'sales_group',
        ['sales_group_id'], ['id'], ondelete='SET NULL',
    )
    # ### end Alembic commands ###

    for table in _RLS_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY tenant_isolation ON {table} "
            f"USING ({_RLS_POLICY_EXPR}) WITH CHECK ({_RLS_POLICY_EXPR})"
        )


def downgrade() -> None:
    """Downgrade schema."""
    for table in reversed(_RLS_TABLES):
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
        op.execute(f"ALTER TABLE {table} NO FORCE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_engagement_sales_group_id', 'engagement', type_='foreignkey')
    op.drop_index(op.f('ix_engagement_sales_group_id'), table_name='engagement')
    op.drop_column('engagement', 'sales_group_id')
    op.drop_column('contract', 'realized_amount')
    op.drop_column('contract', 'external_id')
    op.drop_column('contract', 'external_system')
    op.drop_constraint('fk_account_parent_account_id', 'account', type_='foreignkey')
    op.drop_index(op.f('ix_account_parent_account_id'), table_name='account')
    op.drop_column('account', 'parent_account_id')
    op.drop_index(op.f('ix_sales_group_tenant_id'), table_name='sales_group')
    op.drop_index(op.f('ix_sales_group_parent_group_id'), table_name='sales_group')
    op.drop_table('sales_group')
    # ### end Alembic commands ###
