"""add review_case table and quote/contract export fields

§7.4のRow-Level Securityはreview_caseにも自動で付かないため、
outbox_message/webhook_eventと同じ形でこのマイグレーション自身が張る
(CRM_連携_実装計画.md Phase 1a)。

Revision ID: 1eee666afe2e
Revises: 0943c90da570
Create Date: 2026-08-15 10:02:34.717601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1eee666afe2e'
down_revision: Union[str, Sequence[str], None] = '0943c90da570'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_RLS_TABLES = ["review_case"]
_RLS_POLICY_EXPR = (
    "tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid"
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_case',
    sa.Column('case_no', sa.String(length=32), nullable=False),
    sa.Column('parent_case_no', sa.String(length=32), nullable=True),
    sa.Column('review_type', sa.String(length=16), nullable=False),
    sa.Column('artifact_type', sa.String(length=16), nullable=False),
    sa.Column('quote_id', sa.UUID(), nullable=True),
    sa.Column('contract_id', sa.UUID(), nullable=True),
    sa.Column('engagement_id', sa.UUID(), nullable=False),
    sa.Column('review_key_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider_request_id', sa.String(length=128), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('written_by', sa.String(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagement.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quote_id'], ['quote.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'case_no', name='uq_review_case_tenant_case_no')
    )
    op.create_index(op.f('ix_review_case_case_no'), 'review_case', ['case_no'], unique=False)
    op.create_index(op.f('ix_review_case_contract_id'), 'review_case', ['contract_id'], unique=False)
    op.create_index(op.f('ix_review_case_engagement_id'), 'review_case', ['engagement_id'], unique=False)
    op.create_index(op.f('ix_review_case_quote_id'), 'review_case', ['quote_id'], unique=False)
    op.create_index(op.f('ix_review_case_review_key_hash'), 'review_case', ['review_key_hash'], unique=False)
    op.create_index(op.f('ix_review_case_status'), 'review_case', ['status'], unique=False)
    op.create_index(op.f('ix_review_case_tenant_id'), 'review_case', ['tenant_id'], unique=False)
    op.add_column('contract', sa.Column('destination_country', sa.String(length=2), nullable=True))
    op.add_column('contract', sa.Column('end_user_account_id', sa.UUID(), nullable=True))
    op.add_column('contract', sa.Column('end_use', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'contract', 'account', ['end_user_account_id'], ['id'], ondelete='SET NULL')
    op.add_column('quote', sa.Column('destination_country', sa.String(length=2), nullable=True))
    op.add_column('quote', sa.Column('end_user_account_id', sa.UUID(), nullable=True))
    op.add_column('quote', sa.Column('end_use', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'quote', 'account', ['end_user_account_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###

    for table in _RLS_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY tenant_isolation ON {table} "
            f"USING ({_RLS_POLICY_EXPR}) WITH CHECK ({_RLS_POLICY_EXPR})"
        )


def downgrade() -> None:
    """Downgrade schema."""
    for table in reversed(_RLS_TABLES):
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
        op.execute(f"ALTER TABLE {table} NO FORCE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quote', type_='foreignkey')
    op.drop_column('quote', 'end_use')
    op.drop_column('quote', 'end_user_account_id')
    op.drop_column('quote', 'destination_country')
    op.drop_constraint(None, 'contract', type_='foreignkey')
    op.drop_column('contract', 'end_use')
    op.drop_column('contract', 'end_user_account_id')
    op.drop_column('contract', 'destination_country')
    op.drop_index(op.f('ix_review_case_tenant_id'), table_name='review_case')
    op.drop_index(op.f('ix_review_case_status'), table_name='review_case')
    op.drop_index(op.f('ix_review_case_review_key_hash'), table_name='review_case')
    op.drop_index(op.f('ix_review_case_quote_id'), table_name='review_case')
    op.drop_index(op.f('ix_review_case_engagement_id'), table_name='review_case')
    op.drop_index(op.f('ix_review_case_contract_id'), table_name='review_case')
    op.drop_index(op.f('ix_review_case_case_no'), table_name='review_case')
    op.drop_table('review_case')
    # ### end Alembic commands ###
