"""initial schema: 16 tables

Revision ID: 26c3dac4aa8e
Revises: 
Create Date: 2026-08-12 20:56:02.340281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '26c3dac4aa8e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('corporate_number', sa.String(length=13), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('industry_template', sa.String(length=64), nullable=True),
    sa.Column('external_system', sa.String(length=32), nullable=True),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_system', 'external_id', name='uq_account_external')
    )
    op.create_index(op.f('ix_account_corporate_number'), 'account', ['corporate_number'], unique=False)
    op.create_table('field_autonomy_policy',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('field_path', sa.String(length=96), nullable=False),
    sa.Column('mode', sa.String(length=24), nullable=False),
    sa.Column('auto_apply_threshold', sa.Float(), nullable=False),
    sa.Column('min_samples', sa.Integer(), nullable=False),
    sa.Column('min_model_score', sa.Float(), nullable=False),
    sa.Column('rolling_accept_rate', sa.Float(), nullable=False),
    sa.Column('rolling_sample_size', sa.Integer(), nullable=False),
    sa.Column('last_recomputed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'target_type', 'field_path', name='uq_autonomy_field')
    )
    op.create_index(op.f('ix_field_autonomy_policy_tenant_id'), 'field_autonomy_policy', ['tenant_id'], unique=False)
    op.create_table('gate_policy',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('industry_template', sa.String(length=64), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('strength', sa.String(length=24), nullable=False),
    sa.Column('to_stage', sa.String(length=24), nullable=True),
    sa.Column('artifact_type', sa.String(length=24), nullable=True),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gate_policy_code'), 'gate_policy', ['code'], unique=False)
    op.create_table('compliance_status',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('check_type', sa.String(length=32), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('provider_request_id', sa.String(length=128), nullable=True),
    sa.Column('evidence_uri', sa.String(length=512), nullable=True),
    sa.Column('evidence_hash', sa.String(length=64), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'check_type', name='uq_compliance_current')
    )
    op.create_index('ix_compliance_expiry', 'compliance_status', ['valid_until'], unique=False)
    op.create_index(op.f('ix_compliance_status_account_id'), 'compliance_status', ['account_id'], unique=False)
    op.create_index(op.f('ix_compliance_status_valid_until'), 'compliance_status', ['valid_until'], unique=False)
    op.create_table('contact',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('org_unit', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('left_company_at', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_account_id'), 'contact', ['account_id'], unique=False)
    op.create_index(op.f('ix_contact_email'), 'contact', ['email'], unique=False)
    op.create_table('engagement',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('stage', sa.String(length=24), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('expected_close_date', sa.Date(), nullable=True),
    sa.Column('derived_close_date', sa.Date(), nullable=True),
    sa.Column('external_system', sa.String(length=32), nullable=True),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_system', 'external_id', name='uq_engagement_external')
    )
    op.create_index(op.f('ix_engagement_account_id'), 'engagement', ['account_id'], unique=False)
    op.create_index(op.f('ix_engagement_stage'), 'engagement', ['stage'], unique=False)
    op.create_table('gate_evaluation',
    sa.Column('engagement_id', sa.UUID(), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('policy_version', sa.Integer(), nullable=False),
    sa.Column('satisfied', sa.Boolean(), nullable=False),
    sa.Column('missing', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagement.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['policy_id'], ['gate_policy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gate_evaluation_engagement_id'), 'gate_evaluation', ['engagement_id'], unique=False)
    op.create_table('graph_node',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('placeholder_label', sa.String(length=120), nullable=True),
    sa.Column('org_unit', sa.String(length=120), nullable=True),
    sa.Column('seniority_layer', sa.SmallInteger(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('written_by', sa.String(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.CheckConstraint('contact_id IS NOT NULL OR placeholder_label IS NOT NULL', name='ck_node_identifiable'),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graph_node_account_id'), 'graph_node', ['account_id'], unique=False)
    op.create_index('ix_node_account_layer', 'graph_node', ['account_id', 'seniority_layer'], unique=False)
    op.create_table('ingestion_source',
    sa.Column('engagement_id', sa.UUID(), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('uri', sa.String(length=512), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('participants', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('extractor_version', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagement.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_source_account_id'), 'ingestion_source', ['account_id'], unique=False)
    op.create_index(op.f('ix_ingestion_source_engagement_id'), 'ingestion_source', ['engagement_id'], unique=False)
    op.create_index('ix_source_unprocessed', 'ingestion_source', ['processed_at'], unique=False)
    op.create_table('pipeline_snapshot',
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('engagement_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.String(length=24), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('evidence_score', sa.Float(), nullable=False),
    sa.Column('expected_close_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagement.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_date', 'engagement_id', name='uq_snapshot_daily')
    )
    op.create_index(op.f('ix_pipeline_snapshot_engagement_id'), 'pipeline_snapshot', ['engagement_id'], unique=False)
    op.create_index(op.f('ix_pipeline_snapshot_snapshot_date'), 'pipeline_snapshot', ['snapshot_date'], unique=False)
    op.create_table('qualification_slot',
    sa.Column('engagement_id', sa.UUID(), nullable=False),
    sa.Column('criterion', sa.String(length=32), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('evidence_source_id', sa.UUID(), nullable=True),
    sa.Column('evidence_quote', sa.Text(), nullable=True),
    sa.Column('asserted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decays_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('written_by', sa.String(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagement.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('engagement_id', 'criterion', name='uq_slot_per_deal')
    )
    op.create_index(op.f('ix_qualification_slot_decays_at'), 'qualification_slot', ['decays_at'], unique=False)
    op.create_index(op.f('ix_qualification_slot_engagement_id'), 'qualification_slot', ['engagement_id'], unique=False)
    op.create_table('stage_transition',
    sa.Column('engagement_id', sa.UUID(), nullable=False),
    sa.Column('from_stage', sa.String(length=24), nullable=True),
    sa.Column('to_stage', sa.String(length=24), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gate_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('waiver_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('written_by', sa.String(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagement.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stage_transition_engagement_id'), 'stage_transition', ['engagement_id'], unique=False)
    op.create_table('waiver',
    sa.Column('engagement_id', sa.UUID(), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('written_by', sa.String(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagement.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['policy_id'], ['gate_policy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waiver_engagement_id'), 'waiver', ['engagement_id'], unique=False)
    op.create_table('engagement_role',
    sa.Column('engagement_id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('roles', postgresql.ARRAY(sa.String(length=24)), nullable=False),
    sa.Column('stance', sa.String(length=16), nullable=False),
    sa.Column('influence', sa.SmallInteger(), nullable=False),
    sa.Column('access_level', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('last_touched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('written_by', sa.String(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.CheckConstraint('influence BETWEEN 1 AND 5', name='ck_role_influence'),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagement.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_id'], ['graph_node.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('engagement_id', 'node_id', name='uq_role_per_deal')
    )
    op.create_index(op.f('ix_engagement_role_engagement_id'), 'engagement_role', ['engagement_id'], unique=False)
    op.create_index(op.f('ix_engagement_role_node_id'), 'engagement_role', ['node_id'], unique=False)
    op.create_table('extraction_proposal',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('engagement_id', sa.UUID(), nullable=True),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('field_path', sa.String(length=96), nullable=False),
    sa.Column('current_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('proposed_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_score', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('evidence_quote', sa.Text(), nullable=True),
    sa.Column('evidence_offset', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('decided_by', sa.UUID(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('corrected_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagement.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['ingestion_source.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extraction_proposal_engagement_id'), 'extraction_proposal', ['engagement_id'], unique=False)
    op.create_index(op.f('ix_extraction_proposal_source_id'), 'extraction_proposal', ['source_id'], unique=False)
    op.create_index(op.f('ix_extraction_proposal_status'), 'extraction_proposal', ['status'], unique=False)
    op.create_index('ix_proposal_pending', 'extraction_proposal', ['engagement_id', 'status'], unique=False)
    op.create_table('graph_edge',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('from_node_id', sa.UUID(), nullable=False),
    sa.Column('to_node_id', sa.UUID(), nullable=False),
    sa.Column('edge_type', sa.String(length=24), nullable=False),
    sa.Column('sequence', sa.SmallInteger(), nullable=True),
    sa.Column('strength', sa.SmallInteger(), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('evidence_source_id', sa.UUID(), nullable=True),
    sa.Column('evidence_quote', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('written_by', sa.String(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.CheckConstraint('from_node_id <> to_node_id', name='ck_edge_no_self'),
    sa.CheckConstraint('strength BETWEEN 1 AND 5', name='ck_edge_strength'),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_node_id'], ['graph_node.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_node_id'], ['graph_node.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_node_id', 'to_node_id', 'edge_type', name='uq_edge_unique')
    )
    op.create_index(op.f('ix_graph_edge_account_id'), 'graph_edge', ['account_id'], unique=False)
    op.create_index(op.f('ix_graph_edge_from_node_id'), 'graph_edge', ['from_node_id'], unique=False)
    op.create_index(op.f('ix_graph_edge_to_node_id'), 'graph_edge', ['to_node_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_graph_edge_to_node_id'), table_name='graph_edge')
    op.drop_index(op.f('ix_graph_edge_from_node_id'), table_name='graph_edge')
    op.drop_index(op.f('ix_graph_edge_account_id'), table_name='graph_edge')
    op.drop_table('graph_edge')
    op.drop_index('ix_proposal_pending', table_name='extraction_proposal')
    op.drop_index(op.f('ix_extraction_proposal_status'), table_name='extraction_proposal')
    op.drop_index(op.f('ix_extraction_proposal_source_id'), table_name='extraction_proposal')
    op.drop_index(op.f('ix_extraction_proposal_engagement_id'), table_name='extraction_proposal')
    op.drop_table('extraction_proposal')
    op.drop_index(op.f('ix_engagement_role_node_id'), table_name='engagement_role')
    op.drop_index(op.f('ix_engagement_role_engagement_id'), table_name='engagement_role')
    op.drop_table('engagement_role')
    op.drop_index(op.f('ix_waiver_engagement_id'), table_name='waiver')
    op.drop_table('waiver')
    op.drop_index(op.f('ix_stage_transition_engagement_id'), table_name='stage_transition')
    op.drop_table('stage_transition')
    op.drop_index(op.f('ix_qualification_slot_engagement_id'), table_name='qualification_slot')
    op.drop_index(op.f('ix_qualification_slot_decays_at'), table_name='qualification_slot')
    op.drop_table('qualification_slot')
    op.drop_index(op.f('ix_pipeline_snapshot_snapshot_date'), table_name='pipeline_snapshot')
    op.drop_index(op.f('ix_pipeline_snapshot_engagement_id'), table_name='pipeline_snapshot')
    op.drop_table('pipeline_snapshot')
    op.drop_index('ix_source_unprocessed', table_name='ingestion_source')
    op.drop_index(op.f('ix_ingestion_source_engagement_id'), table_name='ingestion_source')
    op.drop_index(op.f('ix_ingestion_source_account_id'), table_name='ingestion_source')
    op.drop_table('ingestion_source')
    op.drop_index('ix_node_account_layer', table_name='graph_node')
    op.drop_index(op.f('ix_graph_node_account_id'), table_name='graph_node')
    op.drop_table('graph_node')
    op.drop_index(op.f('ix_gate_evaluation_engagement_id'), table_name='gate_evaluation')
    op.drop_table('gate_evaluation')
    op.drop_index(op.f('ix_engagement_stage'), table_name='engagement')
    op.drop_index(op.f('ix_engagement_account_id'), table_name='engagement')
    op.drop_table('engagement')
    op.drop_index(op.f('ix_contact_email'), table_name='contact')
    op.drop_index(op.f('ix_contact_account_id'), table_name='contact')
    op.drop_table('contact')
    op.drop_index(op.f('ix_compliance_status_valid_until'), table_name='compliance_status')
    op.drop_index(op.f('ix_compliance_status_account_id'), table_name='compliance_status')
    op.drop_index('ix_compliance_expiry', table_name='compliance_status')
    op.drop_table('compliance_status')
    op.drop_index(op.f('ix_gate_policy_code'), table_name='gate_policy')
    op.drop_table('gate_policy')
    op.drop_index(op.f('ix_field_autonomy_policy_tenant_id'), table_name='field_autonomy_policy')
    op.drop_table('field_autonomy_policy')
    op.drop_index(op.f('ix_account_corporate_number'), table_name='account')
    op.drop_table('account')
    # ### end Alembic commands ###
