"""add verification fields to qualification_slot

Revision ID: 3cec7569c151
Revises: f0e5faa4fde8
Create Date: 2026-08-13 09:31:04.193145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cec7569c151'
down_revision: Union[str, Sequence[str], None] = 'f0e5faa4fde8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qualification_slot', sa.Column('evidence_uri', sa.String(length=512), nullable=True))
    op.add_column('qualification_slot', sa.Column('verification_method', sa.String(length=32), nullable=True))
    op.add_column('qualification_slot', sa.Column('verification_note', sa.Text(), nullable=True))
    op.add_column('qualification_slot', sa.Column('verified_by', sa.UUID(), nullable=True))
    op.add_column('qualification_slot', sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qualification_slot', 'verified_at')
    op.drop_column('qualification_slot', 'verified_by')
    op.drop_column('qualification_slot', 'verification_note')
    op.drop_column('qualification_slot', 'verification_method')
    op.drop_column('qualification_slot', 'evidence_uri')
    # ### end Alembic commands ###
