"""add account aitm_party_id

Revision ID: 3f91257858dd
Revises: 1eee666afe2e
Create Date: 2026-08-15 19:29:02.888098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f91257858dd'
down_revision: Union[str, Sequence[str], None] = '1eee666afe2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('aitm_party_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_account_aitm_party_id'), 'account', ['aitm_party_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_account_aitm_party_id'), table_name='account')
    op.drop_column('account', 'aitm_party_id')
    # ### end Alembic commands ###
