"""add report_snapshot table

§7.4 で確定した Row-Level Security によるテナント分離は新規テナント
スコープ付きテーブルには自動で付かない。report_snapshot にこのマイグレー
ション自身で ENABLE/FORCE RLS + POLICY を張る(weekly_review と同じ形)。

Revision ID: 4fbd42e00887
Revises: 82df2c8b7c29
Create Date: 2026-08-14 16:16:34.560767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4fbd42e00887'
down_revision: Union[str, Sequence[str], None] = '82df2c8b7c29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_RLS_TABLES = ["report_snapshot"]
_RLS_POLICY_EXPR = (
    "tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid"
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_snapshot',
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('written_by', sa.String(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'snapshot_date', name='uq_report_snapshot_date')
    )
    op.create_index(op.f('ix_report_snapshot_snapshot_date'), 'report_snapshot', ['snapshot_date'], unique=False)
    op.create_index(op.f('ix_report_snapshot_tenant_id'), 'report_snapshot', ['tenant_id'], unique=False)
    # ### end Alembic commands ###

    for table in _RLS_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY tenant_isolation ON {table} "
            f"USING ({_RLS_POLICY_EXPR}) WITH CHECK ({_RLS_POLICY_EXPR})"
        )


def downgrade() -> None:
    """Downgrade schema."""
    for table in reversed(_RLS_TABLES):
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
        op.execute(f"ALTER TABLE {table} NO FORCE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_snapshot_tenant_id'), table_name='report_snapshot')
    op.drop_index(op.f('ix_report_snapshot_snapshot_date'), table_name='report_snapshot')
    op.drop_table('report_snapshot')
    # ### end Alembic commands ###
