"""add lost_reason, harmonize owner field, add lead conversion snapshot

Revision ID: 52b0ee29bbd1
Revises: a75ae846151c
Create Date: 2026-08-13 15:50:00.280078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '52b0ee29bbd1'
down_revision: Union[str, Sequence[str], None] = 'a75ae846151c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('engagement', sa.Column('owner', sa.String(length=120), nullable=True))
    op.add_column('engagement', sa.Column('lost_reason', sa.Text(), nullable=True))
    op.drop_column('engagement', 'owner_id')
    op.add_column('lead', sa.Column(
        'conversion_snapshot', postgresql.JSONB(astext_type=sa.Text()),
        nullable=False, server_default='{}',
    ))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lead', 'conversion_snapshot')
    op.add_column('engagement', sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_column('engagement', 'lost_reason')
    op.drop_column('engagement', 'owner')
    # ### end Alembic commands ###
