"""add weekly_review table

§7.4 で確定した Row-Level Security によるテナント分離は新規テナント
スコープ付きテーブルには自動で付かない。weekly_review にこのマイグレー
ション自身で ENABLE/FORCE RLS + POLICY を張る。

Revision ID: 82df2c8b7c29
Revises: 07bcc768b039
Create Date: 2026-08-14 09:58:38.457011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82df2c8b7c29'
down_revision: Union[str, Sequence[str], None] = '07bcc768b039'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_RLS_TABLES = ["weekly_review"]
_RLS_POLICY_EXPR = (
    "tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid"
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_review',
    sa.Column('engagement_id', sa.UUID(), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('rep_comment', sa.Text(), nullable=True),
    sa.Column('manager_comment', sa.Text(), nullable=True),
    sa.Column('manager_status', sa.String(length=16), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('written_by', sa.String(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagement.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'engagement_id', 'week_start_date', name='uq_weekly_review_week')
    )
    op.create_index(op.f('ix_weekly_review_engagement_id'), 'weekly_review', ['engagement_id'], unique=False)
    op.create_index(op.f('ix_weekly_review_tenant_id'), 'weekly_review', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_weekly_review_week_start_date'), 'weekly_review', ['week_start_date'], unique=False)
    # ### end Alembic commands ###

    for table in _RLS_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY tenant_isolation ON {table} "
            f"USING ({_RLS_POLICY_EXPR}) WITH CHECK ({_RLS_POLICY_EXPR})"
        )


def downgrade() -> None:
    """Downgrade schema."""
    for table in reversed(_RLS_TABLES):
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
        op.execute(f"ALTER TABLE {table} NO FORCE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weekly_review_week_start_date'), table_name='weekly_review')
    op.drop_index(op.f('ix_weekly_review_tenant_id'), table_name='weekly_review')
    op.drop_index(op.f('ix_weekly_review_engagement_id'), table_name='weekly_review')
    op.drop_table('weekly_review')
    # ### end Alembic commands ###
