"""add rep_comment to extraction_proposal

Revision ID: 869bc22447bd
Revises: 766b53dbe968
Create Date: 2026-08-13 13:38:38.053318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '869bc22447bd'
down_revision: Union[str, Sequence[str], None] = '766b53dbe968'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extraction_proposal', sa.Column('rep_comment', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('extraction_proposal', 'rep_comment')
    # ### end Alembic commands ###
