"""add product, engagement line items, quote, contract

§7.4 で確定した Row-Level Security によるテナント分離(766b53dbe968)は
新規テナントスコープ付きテーブルには自動で付かない。この6テーブルに
同じ ENABLE/FORCE RLS + POLICY をこのマイグレーション自身で張る。

Revision ID: 880195fb5460
Revises: 52b0ee29bbd1
Create Date: 2026-08-13 16:26:18.295272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '880195fb5460'
down_revision: Union[str, Sequence[str], None] = '52b0ee29bbd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_RLS_TABLES = [
    "product", "engagement_line_item", "quote", "contract",
    "quote_line_item", "contract_line_item",
]
_RLS_POLICY_EXPR = (
    "tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid"
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=True),
    sa.Column('list_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_tenant_id'), 'product', ['tenant_id'], unique=False)
    op.create_table('engagement_line_item',
    sa.Column('engagement_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('product_name_snapshot', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('list_price_snapshot', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('discount_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagement.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_engagement_line_item_engagement_id'), 'engagement_line_item', ['engagement_id'], unique=False)
    op.create_index(op.f('ix_engagement_line_item_product_id'), 'engagement_line_item', ['product_id'], unique=False)
    op.create_index(op.f('ix_engagement_line_item_tenant_id'), 'engagement_line_item', ['tenant_id'], unique=False)
    op.create_table('quote',
    sa.Column('engagement_id', sa.UUID(), nullable=False),
    sa.Column('quote_number', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('written_by', sa.String(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagement.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quote_engagement_id'), 'quote', ['engagement_id'], unique=False)
    op.create_index(op.f('ix_quote_quote_number'), 'quote', ['quote_number'], unique=False)
    op.create_index(op.f('ix_quote_status'), 'quote', ['status'], unique=False)
    op.create_index(op.f('ix_quote_tenant_id'), 'quote', ['tenant_id'], unique=False)
    op.create_table('contract',
    sa.Column('engagement_id', sa.UUID(), nullable=False),
    sa.Column('quote_id', sa.UUID(), nullable=True),
    sa.Column('contract_number', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('written_by', sa.String(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagement.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quote_id'], ['quote.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_contract_number'), 'contract', ['contract_number'], unique=False)
    op.create_index(op.f('ix_contract_engagement_id'), 'contract', ['engagement_id'], unique=False)
    op.create_index(op.f('ix_contract_quote_id'), 'contract', ['quote_id'], unique=False)
    op.create_index(op.f('ix_contract_status'), 'contract', ['status'], unique=False)
    op.create_index(op.f('ix_contract_tenant_id'), 'contract', ['tenant_id'], unique=False)
    op.create_table('quote_line_item',
    sa.Column('quote_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('product_name_snapshot', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('list_price_snapshot', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('discount_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quote_id'], ['quote.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quote_line_item_quote_id'), 'quote_line_item', ['quote_id'], unique=False)
    op.create_index(op.f('ix_quote_line_item_tenant_id'), 'quote_line_item', ['tenant_id'], unique=False)
    op.create_table('contract_line_item',
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('product_name_snapshot', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('list_price_snapshot', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('discount_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_line_item_contract_id'), 'contract_line_item', ['contract_id'], unique=False)
    op.create_index(op.f('ix_contract_line_item_tenant_id'), 'contract_line_item', ['tenant_id'], unique=False)
    # ### end Alembic commands ###

    for table in _RLS_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY tenant_isolation ON {table} "
            f"USING ({_RLS_POLICY_EXPR}) WITH CHECK ({_RLS_POLICY_EXPR})"
        )


def downgrade() -> None:
    """Downgrade schema."""
    for table in reversed(_RLS_TABLES):
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
        op.execute(f"ALTER TABLE {table} NO FORCE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contract_line_item_tenant_id'), table_name='contract_line_item')
    op.drop_index(op.f('ix_contract_line_item_contract_id'), table_name='contract_line_item')
    op.drop_table('contract_line_item')
    op.drop_index(op.f('ix_quote_line_item_tenant_id'), table_name='quote_line_item')
    op.drop_index(op.f('ix_quote_line_item_quote_id'), table_name='quote_line_item')
    op.drop_table('quote_line_item')
    op.drop_index(op.f('ix_contract_tenant_id'), table_name='contract')
    op.drop_index(op.f('ix_contract_status'), table_name='contract')
    op.drop_index(op.f('ix_contract_quote_id'), table_name='contract')
    op.drop_index(op.f('ix_contract_engagement_id'), table_name='contract')
    op.drop_index(op.f('ix_contract_contract_number'), table_name='contract')
    op.drop_table('contract')
    op.drop_index(op.f('ix_quote_tenant_id'), table_name='quote')
    op.drop_index(op.f('ix_quote_status'), table_name='quote')
    op.drop_index(op.f('ix_quote_quote_number'), table_name='quote')
    op.drop_index(op.f('ix_quote_engagement_id'), table_name='quote')
    op.drop_table('quote')
    op.drop_index(op.f('ix_engagement_line_item_tenant_id'), table_name='engagement_line_item')
    op.drop_index(op.f('ix_engagement_line_item_product_id'), table_name='engagement_line_item')
    op.drop_index(op.f('ix_engagement_line_item_engagement_id'), table_name='engagement_line_item')
    op.drop_table('engagement_line_item')
    op.drop_index(op.f('ix_product_tenant_id'), table_name='product')
    op.drop_table('product')
    # ### end Alembic commands ###
