"""add sequence automation tables

§7.4 で確定した Row-Level Security によるテナント分離(766b53dbe968)は
新規テナントスコープ付きテーブルには自動で付かない。sequence /
sequence_step / sequence_enrollment / sequence_draft の4テーブルに
同じ ENABLE/FORCE RLS + POLICY をこのマイグレーション自身で張る。

Revision ID: 9d4652682bcc
Revises: deea722fe994
Create Date: 2026-08-13 14:57:28.223508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d4652682bcc'
down_revision: Union[str, Sequence[str], None] = 'deea722fe994'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_RLS_TABLES = ["sequence", "sequence_step", "sequence_enrollment", "sequence_draft"]
_RLS_POLICY_EXPR = (
    "tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid"
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sequence',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('written_by', sa.String(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sequence_tenant_id'), 'sequence', ['tenant_id'], unique=False)
    op.create_table('sequence_enrollment',
    sa.Column('sequence_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('current_step_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('next_action_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('written_by', sa.String(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sequence_id'], ['sequence.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sequence_enrollment_lead_id'), 'sequence_enrollment', ['lead_id'], unique=False)
    op.create_index(op.f('ix_sequence_enrollment_sequence_id'), 'sequence_enrollment', ['sequence_id'], unique=False)
    op.create_index(op.f('ix_sequence_enrollment_status'), 'sequence_enrollment', ['status'], unique=False)
    op.create_index(op.f('ix_sequence_enrollment_tenant_id'), 'sequence_enrollment', ['tenant_id'], unique=False)
    op.create_table('sequence_step',
    sa.Column('sequence_id', sa.UUID(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('delay_days', sa.Integer(), nullable=False),
    sa.Column('subject_template', sa.String(length=255), nullable=True),
    sa.Column('body_template', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['sequence_id'], ['sequence.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sequence_id', 'step_order', name='uq_sequence_step_order')
    )
    op.create_index(op.f('ix_sequence_step_sequence_id'), 'sequence_step', ['sequence_id'], unique=False)
    op.create_index(op.f('ix_sequence_step_tenant_id'), 'sequence_step', ['tenant_id'], unique=False)
    op.create_table('sequence_draft',
    sa.Column('enrollment_id', sa.UUID(), nullable=False),
    sa.Column('step_id', sa.UUID(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('personalization_note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.String(length=120), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['sequence_enrollment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['sequence_step.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sequence_draft_enrollment_id'), 'sequence_draft', ['enrollment_id'], unique=False)
    op.create_index(op.f('ix_sequence_draft_status'), 'sequence_draft', ['status'], unique=False)
    op.create_index(op.f('ix_sequence_draft_tenant_id'), 'sequence_draft', ['tenant_id'], unique=False)
    # ### end Alembic commands ###

    for table in _RLS_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY tenant_isolation ON {table} "
            f"USING ({_RLS_POLICY_EXPR}) WITH CHECK ({_RLS_POLICY_EXPR})"
        )


def downgrade() -> None:
    """Downgrade schema."""
    for table in reversed(_RLS_TABLES):
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
        op.execute(f"ALTER TABLE {table} NO FORCE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sequence_draft_tenant_id'), table_name='sequence_draft')
    op.drop_index(op.f('ix_sequence_draft_status'), table_name='sequence_draft')
    op.drop_index(op.f('ix_sequence_draft_enrollment_id'), table_name='sequence_draft')
    op.drop_table('sequence_draft')
    op.drop_index(op.f('ix_sequence_step_tenant_id'), table_name='sequence_step')
    op.drop_index(op.f('ix_sequence_step_sequence_id'), table_name='sequence_step')
    op.drop_table('sequence_step')
    op.drop_index(op.f('ix_sequence_enrollment_tenant_id'), table_name='sequence_enrollment')
    op.drop_index(op.f('ix_sequence_enrollment_status'), table_name='sequence_enrollment')
    op.drop_index(op.f('ix_sequence_enrollment_sequence_id'), table_name='sequence_enrollment')
    op.drop_index(op.f('ix_sequence_enrollment_lead_id'), table_name='sequence_enrollment')
    op.drop_table('sequence_enrollment')
    op.drop_index(op.f('ix_sequence_tenant_id'), table_name='sequence')
    op.drop_table('sequence')
    # ### end Alembic commands ###
