"""add sequence branching fields

Revision ID: a75ae846151c
Revises: 9d4652682bcc
Create Date: 2026-08-13 15:17:13.873313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a75ae846151c'
down_revision: Union[str, Sequence[str], None] = '9d4652682bcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sequence_enrollment', 'current_step_order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('sequence_step', sa.Column(
        'reaction_channels', postgresql.JSONB(astext_type=sa.Text()),
        nullable=False, server_default='[]',
    ))
    op.add_column('sequence_step', sa.Column('on_reaction_next_order', sa.Integer(), nullable=True))
    op.add_column('sequence_step', sa.Column('on_no_reaction_next_order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sequence_step', 'on_no_reaction_next_order')
    op.drop_column('sequence_step', 'on_reaction_next_order')
    op.drop_column('sequence_step', 'reaction_channels')
    op.alter_column('sequence_enrollment', 'current_step_order',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
