"""add erp_material, product_group, product links

§7.4 で確定した Row-Level Security によるテナント分離は新規テナント
スコープ付きテーブルには自動で付かない。erp_material / product_group の
2テーブルにこのマイグレーション自身で ENABLE/FORCE RLS + POLICY を張る
(product テーブルは既存マイグレーション 880195fb5460 で対応済みなので、
列を追加するだけのここでは不要)。

Revision ID: b1d2e4a20055
Revises: 880195fb5460
Create Date: 2026-08-13 18:21:32.423515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1d2e4a20055'
down_revision: Union[str, Sequence[str], None] = '880195fb5460'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_RLS_TABLES = ["erp_material", "product_group"]
_RLS_POLICY_EXPR = (
    "tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid"
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('erp_material',
    sa.Column('material_code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('material_type', sa.String(length=10), nullable=False),
    sa.Column('base_unit', sa.String(length=5), nullable=False),
    sa.Column('standard_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('hs_code', sa.String(length=20), nullable=True),
    sa.Column('eccn', sa.String(length=20), nullable=True),
    sa.Column('fefta_judgment', sa.String(length=20), nullable=False),
    sa.Column('country_of_origin', sa.String(length=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'material_code', name='uq_erp_material_tenant_code')
    )
    op.create_index(op.f('ix_erp_material_material_code'), 'erp_material', ['material_code'], unique=False)
    op.create_index(op.f('ix_erp_material_tenant_id'), 'erp_material', ['tenant_id'], unique=False)
    op.create_table('product_group',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('parent_group_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['parent_group_id'], ['product_group.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_group_parent_group_id'), 'product_group', ['parent_group_id'], unique=False)
    op.create_index(op.f('ix_product_group_tenant_id'), 'product_group', ['tenant_id'], unique=False)
    op.add_column('product', sa.Column('erp_material_id', sa.UUID(), nullable=True))
    op.add_column('product', sa.Column('product_group_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_product_erp_material_id'), 'product', ['erp_material_id'], unique=False)
    op.create_index(op.f('ix_product_product_group_id'), 'product', ['product_group_id'], unique=False)
    op.create_foreign_key(
        'fk_product_product_group_id', 'product', 'product_group',
        ['product_group_id'], ['id'], ondelete='SET NULL',
    )
    op.create_foreign_key(
        'fk_product_erp_material_id', 'product', 'erp_material',
        ['erp_material_id'], ['id'], ondelete='SET NULL',
    )
    # ### end Alembic commands ###

    for table in _RLS_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY tenant_isolation ON {table} "
            f"USING ({_RLS_POLICY_EXPR}) WITH CHECK ({_RLS_POLICY_EXPR})"
        )


def downgrade() -> None:
    """Downgrade schema."""
    for table in reversed(_RLS_TABLES):
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
        op.execute(f"ALTER TABLE {table} NO FORCE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_product_erp_material_id', 'product', type_='foreignkey')
    op.drop_constraint('fk_product_product_group_id', 'product', type_='foreignkey')
    op.drop_index(op.f('ix_product_product_group_id'), table_name='product')
    op.drop_index(op.f('ix_product_erp_material_id'), table_name='product')
    op.drop_column('product', 'product_group_id')
    op.drop_column('product', 'erp_material_id')
    op.drop_index(op.f('ix_product_group_tenant_id'), table_name='product_group')
    op.drop_index(op.f('ix_product_group_parent_group_id'), table_name='product_group')
    op.drop_table('product_group')
    op.drop_index(op.f('ix_erp_material_tenant_id'), table_name='erp_material')
    op.drop_index(op.f('ix_erp_material_material_code'), table_name='erp_material')
    op.drop_table('erp_material')
    # ### end Alembic commands ###
