"""add phase4 license, deemed export, rnd, monitoring fields

§7.4のRow-Level Securityはlicense_allocationにも自動で付かないため、
このマイグレーション自身が張る(Phase 0以降の踏襲パターン)。

Revision ID: bf6015bcc588
Revises: c2f2e6567bbd
Create Date: 2026-08-15 19:56:21.459583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bf6015bcc588'
down_revision: Union[str, Sequence[str], None] = 'c2f2e6567bbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_RLS_TABLES = ["license_allocation"]
_RLS_POLICY_EXPR = (
    "tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid"
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('license_allocation',
    sa.Column('quote_id', sa.UUID(), nullable=True),
    sa.Column('contract_id', sa.UUID(), nullable=True),
    sa.Column('engagement_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('license_number', sa.String(length=64), nullable=True),
    sa.Column('allocation_id', sa.String(length=64), nullable=True),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('allocated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('written_by', sa.String(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagement.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quote_id'], ['quote.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_license_allocation_contract_id'), 'license_allocation', ['contract_id'], unique=False)
    op.create_index(op.f('ix_license_allocation_engagement_id'), 'license_allocation', ['engagement_id'], unique=False)
    op.create_index(op.f('ix_license_allocation_quote_id'), 'license_allocation', ['quote_id'], unique=False)
    op.create_index(op.f('ix_license_allocation_status'), 'license_allocation', ['status'], unique=False)
    op.create_index(op.f('ix_license_allocation_tenant_id'), 'license_allocation', ['tenant_id'], unique=False)
    op.add_column('contact', sa.Column('nationality', sa.String(length=2), nullable=True))
    op.add_column('contract', sa.Column('monitoring_alert', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('contract', sa.Column('monitoring_alert_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('engagement', sa.Column('aitm_rnd_case_id', sa.String(length=64), nullable=True))
    op.add_column('engagement', sa.Column('exclude_from_pipeline', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.create_index(op.f('ix_engagement_aitm_rnd_case_id'), 'engagement', ['aitm_rnd_case_id'], unique=False)
    op.add_column('ingestion_source', sa.Column('involves_technical_disclosure', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('ingestion_source', sa.Column('deemed_export_event_type', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###

    for table in _RLS_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY tenant_isolation ON {table} "
            f"USING ({_RLS_POLICY_EXPR}) WITH CHECK ({_RLS_POLICY_EXPR})"
        )


def downgrade() -> None:
    """Downgrade schema."""
    for table in reversed(_RLS_TABLES):
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
        op.execute(f"ALTER TABLE {table} NO FORCE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingestion_source', 'deemed_export_event_type')
    op.drop_column('ingestion_source', 'involves_technical_disclosure')
    op.drop_index(op.f('ix_engagement_aitm_rnd_case_id'), table_name='engagement')
    op.drop_column('engagement', 'exclude_from_pipeline')
    op.drop_column('engagement', 'aitm_rnd_case_id')
    op.drop_column('contract', 'monitoring_alert_detail')
    op.drop_column('contract', 'monitoring_alert')
    op.drop_column('contact', 'nationality')
    op.drop_index(op.f('ix_license_allocation_tenant_id'), table_name='license_allocation')
    op.drop_index(op.f('ix_license_allocation_status'), table_name='license_allocation')
    op.drop_index(op.f('ix_license_allocation_quote_id'), table_name='license_allocation')
    op.drop_index(op.f('ix_license_allocation_engagement_id'), table_name='license_allocation')
    op.drop_index(op.f('ix_license_allocation_contract_id'), table_name='license_allocation')
    op.drop_table('license_allocation')
    # ### end Alembic commands ###
