"""add contract_fulfillment table and account erp attributes

§7.4のRow-Level Securityはcontract_fulfillmentにも自動で付かないため、
このマイグレーション自身が張る(Phase 0以降の踏襲パターン)。

Revision ID: c2f2e6567bbd
Revises: 3f91257858dd
Create Date: 2026-08-15 19:41:09.242379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2f2e6567bbd'
down_revision: Union[str, Sequence[str], None] = '3f91257858dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_RLS_TABLES = ["contract_fulfillment"]
_RLS_POLICY_EXPR = (
    "tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid"
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_fulfillment',
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('erp_document_number', sa.String(length=64), nullable=False),
    sa.Column('product_code', sa.String(length=64), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('written_by', sa.String(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'kind', 'erp_document_number', name='uq_contract_fulfillment_tenant_kind_doc')
    )
    op.create_index(op.f('ix_contract_fulfillment_contract_id'), 'contract_fulfillment', ['contract_id'], unique=False)
    op.create_index(op.f('ix_contract_fulfillment_kind'), 'contract_fulfillment', ['kind'], unique=False)
    op.create_index(op.f('ix_contract_fulfillment_tenant_id'), 'contract_fulfillment', ['tenant_id'], unique=False)
    op.add_column('account', sa.Column('credit_limit', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('account', sa.Column('credit_available', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('account', sa.Column('payment_terms_master', sa.String(length=32), nullable=True))
    op.add_column('account', sa.Column('customer_group', sa.String(length=64), nullable=True))
    op.add_column('account', sa.Column('sales_district', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###

    for table in _RLS_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY tenant_isolation ON {table} "
            f"USING ({_RLS_POLICY_EXPR}) WITH CHECK ({_RLS_POLICY_EXPR})"
        )


def downgrade() -> None:
    """Downgrade schema."""
    for table in reversed(_RLS_TABLES):
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
        op.execute(f"ALTER TABLE {table} NO FORCE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'sales_district')
    op.drop_column('account', 'customer_group')
    op.drop_column('account', 'payment_terms_master')
    op.drop_column('account', 'credit_available')
    op.drop_column('account', 'credit_limit')
    op.drop_index(op.f('ix_contract_fulfillment_tenant_id'), table_name='contract_fulfillment')
    op.drop_index(op.f('ix_contract_fulfillment_kind'), table_name='contract_fulfillment')
    op.drop_index(op.f('ix_contract_fulfillment_contract_id'), table_name='contract_fulfillment')
    op.drop_table('contract_fulfillment')
    # ### end Alembic commands ###
