"""add action_item table

§7.4 で確定した Row-Level Security によるテナント分離(766b53dbe968)は
そのマイグレーション時点で存在した16テーブルにしか適用されていない。
新規のテナントスコープ付きテーブルを追加するたびに、このマイグレーション
自身で同じ ENABLE/FORCE RLS + POLICY を張らないと分離が抜ける。

Revision ID: d50c71a01d7b
Revises: 869bc22447bd
Create Date: 2026-08-13 13:56:02.332626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd50c71a01d7b'
down_revision: Union[str, Sequence[str], None] = '869bc22447bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_RLS_POLICY_EXPR = (
    "tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid"
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_item',
    sa.Column('engagement_id', sa.UUID(), nullable=False),
    sa.Column('field_path', sa.String(length=96), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('play', sa.Text(), nullable=True),
    sa.Column('assigned_to', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('written_by', sa.String(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagement.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_item_engagement_id'), 'action_item', ['engagement_id'], unique=False)
    op.create_index('ix_action_item_open', 'action_item', ['engagement_id', 'status'], unique=False)
    op.create_index(op.f('ix_action_item_status'), 'action_item', ['status'], unique=False)
    op.create_index(op.f('ix_action_item_tenant_id'), 'action_item', ['tenant_id'], unique=False)
    # ### end Alembic commands ###

    op.execute("ALTER TABLE action_item ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE action_item FORCE ROW LEVEL SECURITY")
    op.execute(
        f"CREATE POLICY tenant_isolation ON action_item "
        f"USING ({_RLS_POLICY_EXPR}) WITH CHECK ({_RLS_POLICY_EXPR})"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON action_item")
    op.execute("ALTER TABLE action_item NO FORCE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE action_item DISABLE ROW LEVEL SECURITY")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_action_item_tenant_id'), table_name='action_item')
    op.drop_index(op.f('ix_action_item_status'), table_name='action_item')
    op.drop_index('ix_action_item_open', table_name='action_item')
    op.drop_index(op.f('ix_action_item_engagement_id'), table_name='action_item')
    op.drop_table('action_item')
    # ### end Alembic commands ###
