"""add engagement parent_engagement_id and relationship_type

Revision ID: d987c93b4b20
Revises: d20111fcdac5
Create Date: 2026-08-13 19:22:02.476394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd987c93b4b20'
down_revision: Union[str, Sequence[str], None] = 'd20111fcdac5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('engagement', sa.Column('parent_engagement_id', sa.UUID(), nullable=True))
    op.add_column('engagement', sa.Column('relationship_type', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_engagement_parent_engagement_id'), 'engagement', ['parent_engagement_id'], unique=False)
    op.create_foreign_key(
        'fk_engagement_parent_engagement_id', 'engagement', 'engagement',
        ['parent_engagement_id'], ['id'], ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_engagement_parent_engagement_id', 'engagement', type_='foreignkey')
    op.drop_index(op.f('ix_engagement_parent_engagement_id'), table_name='engagement')
    op.drop_column('engagement', 'relationship_type')
    op.drop_column('engagement', 'parent_engagement_id')
    # ### end Alembic commands ###
