"""add lead, touch, campaign tables and engagement originating_lead_id

§7.4 で確定した Row-Level Security によるテナント分離(766b53dbe968)は
新規テナントスコープ付きテーブルには自動で付かない。campaign/lead/touch
の3テーブルに同じ ENABLE/FORCE RLS + POLICY をこのマイグレーション自身で張る。

Revision ID: deea722fe994
Revises: d50c71a01d7b
Create Date: 2026-08-13 14:18:49.352219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'deea722fe994'
down_revision: Union[str, Sequence[str], None] = 'd50c71a01d7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_RLS_TABLES = ["campaign", "lead", "touch"]
_RLS_POLICY_EXPR = (
    "tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid"
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('channel_type', sa.String(length=24), nullable=False),
    sa.Column('owner_team', sa.String(length=32), nullable=True),
    sa.Column('cost', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_tenant_id'), 'campaign', ['tenant_id'], unique=False)
    op.create_table('lead',
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('matched_account_id', sa.UUID(), nullable=True),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('source_channel', sa.String(length=16), nullable=True),
    sa.Column('source_campaign_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('owner', sa.String(length=120), nullable=True),
    sa.Column('disqualify_reason', sa.Text(), nullable=True),
    sa.Column('converted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('converted_engagement_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('written_by', sa.String(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['converted_engagement_id'], ['engagement.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['matched_account_id'], ['account.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_campaign_id'], ['campaign.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_converted_engagement_id'), 'lead', ['converted_engagement_id'], unique=False)
    op.create_index(op.f('ix_lead_matched_account_id'), 'lead', ['matched_account_id'], unique=False)
    op.create_index(op.f('ix_lead_source_campaign_id'), 'lead', ['source_campaign_id'], unique=False)
    op.create_index(op.f('ix_lead_status'), 'lead', ['status'], unique=False)
    op.create_index(op.f('ix_lead_tenant_id'), 'lead', ['tenant_id'], unique=False)
    op.create_table('touch',
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('channel', sa.String(length=24), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_system', sa.String(length=32), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_touch_campaign_id'), 'touch', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_touch_lead_id'), 'touch', ['lead_id'], unique=False)
    op.create_index(op.f('ix_touch_tenant_id'), 'touch', ['tenant_id'], unique=False)
    op.add_column('engagement', sa.Column('originating_lead_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_engagement_originating_lead_id'), 'engagement', ['originating_lead_id'], unique=False)
    op.create_foreign_key(None, 'engagement', 'lead', ['originating_lead_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###

    for table in _RLS_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY tenant_isolation ON {table} "
            f"USING ({_RLS_POLICY_EXPR}) WITH CHECK ({_RLS_POLICY_EXPR})"
        )


def downgrade() -> None:
    """Downgrade schema."""
    for table in reversed(_RLS_TABLES):
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
        op.execute(f"ALTER TABLE {table} NO FORCE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'engagement', type_='foreignkey')
    op.drop_index(op.f('ix_engagement_originating_lead_id'), table_name='engagement')
    op.drop_column('engagement', 'originating_lead_id')
    op.drop_index(op.f('ix_touch_tenant_id'), table_name='touch')
    op.drop_index(op.f('ix_touch_lead_id'), table_name='touch')
    op.drop_index(op.f('ix_touch_campaign_id'), table_name='touch')
    op.drop_table('touch')
    op.drop_index(op.f('ix_lead_tenant_id'), table_name='lead')
    op.drop_index(op.f('ix_lead_status'), table_name='lead')
    op.drop_index(op.f('ix_lead_source_campaign_id'), table_name='lead')
    op.drop_index(op.f('ix_lead_matched_account_id'), table_name='lead')
    op.drop_index(op.f('ix_lead_converted_engagement_id'), table_name='lead')
    op.drop_table('lead')
    op.drop_index(op.f('ix_campaign_tenant_id'), table_name='campaign')
    op.drop_table('campaign')
    # ### end Alembic commands ###
