"""add tenant_id to all tables

Revision ID: f0e5faa4fde8
Revises: 26c3dac4aa8e
Create Date: 2026-08-12 21:41:50.661940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0e5faa4fde8'
down_revision: Union[str, Sequence[str], None] = '26c3dac4aa8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('uq_account_external'), 'account', type_='unique')
    op.create_unique_constraint('uq_account_external', 'account', ['tenant_id', 'external_system', 'external_id'])
    op.create_index(op.f('ix_account_tenant_id'), 'account', ['tenant_id'], unique=False)
    op.add_column('compliance_status', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_compliance_status_tenant_id'), 'compliance_status', ['tenant_id'], unique=False)
    op.add_column('contact', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_contact_tenant_id'), 'contact', ['tenant_id'], unique=False)
    op.add_column('engagement', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('uq_engagement_external'), 'engagement', type_='unique')
    op.create_unique_constraint('uq_engagement_external', 'engagement', ['tenant_id', 'external_system', 'external_id'])
    op.create_index(op.f('ix_engagement_tenant_id'), 'engagement', ['tenant_id'], unique=False)
    op.add_column('engagement_role', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_engagement_role_tenant_id'), 'engagement_role', ['tenant_id'], unique=False)
    op.add_column('extraction_proposal', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_extraction_proposal_tenant_id'), 'extraction_proposal', ['tenant_id'], unique=False)
    op.add_column('gate_evaluation', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_gate_evaluation_tenant_id'), 'gate_evaluation', ['tenant_id'], unique=False)
    op.add_column('gate_policy', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_gate_policy_tenant_id'), 'gate_policy', ['tenant_id'], unique=False)
    op.add_column('graph_edge', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_graph_edge_tenant_id'), 'graph_edge', ['tenant_id'], unique=False)
    op.add_column('graph_node', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_graph_node_tenant_id'), 'graph_node', ['tenant_id'], unique=False)
    op.add_column('ingestion_source', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_ingestion_source_tenant_id'), 'ingestion_source', ['tenant_id'], unique=False)
    op.add_column('pipeline_snapshot', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_pipeline_snapshot_tenant_id'), 'pipeline_snapshot', ['tenant_id'], unique=False)
    op.add_column('qualification_slot', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_qualification_slot_tenant_id'), 'qualification_slot', ['tenant_id'], unique=False)
    op.add_column('stage_transition', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_stage_transition_tenant_id'), 'stage_transition', ['tenant_id'], unique=False)
    op.add_column('waiver', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_waiver_tenant_id'), 'waiver', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_waiver_tenant_id'), table_name='waiver')
    op.drop_column('waiver', 'tenant_id')
    op.drop_index(op.f('ix_stage_transition_tenant_id'), table_name='stage_transition')
    op.drop_column('stage_transition', 'tenant_id')
    op.drop_index(op.f('ix_qualification_slot_tenant_id'), table_name='qualification_slot')
    op.drop_column('qualification_slot', 'tenant_id')
    op.drop_index(op.f('ix_pipeline_snapshot_tenant_id'), table_name='pipeline_snapshot')
    op.drop_column('pipeline_snapshot', 'tenant_id')
    op.drop_index(op.f('ix_ingestion_source_tenant_id'), table_name='ingestion_source')
    op.drop_column('ingestion_source', 'tenant_id')
    op.drop_index(op.f('ix_graph_node_tenant_id'), table_name='graph_node')
    op.drop_column('graph_node', 'tenant_id')
    op.drop_index(op.f('ix_graph_edge_tenant_id'), table_name='graph_edge')
    op.drop_column('graph_edge', 'tenant_id')
    op.drop_index(op.f('ix_gate_policy_tenant_id'), table_name='gate_policy')
    op.drop_column('gate_policy', 'tenant_id')
    op.drop_index(op.f('ix_gate_evaluation_tenant_id'), table_name='gate_evaluation')
    op.drop_column('gate_evaluation', 'tenant_id')
    op.drop_index(op.f('ix_extraction_proposal_tenant_id'), table_name='extraction_proposal')
    op.drop_column('extraction_proposal', 'tenant_id')
    op.drop_index(op.f('ix_engagement_role_tenant_id'), table_name='engagement_role')
    op.drop_column('engagement_role', 'tenant_id')
    op.drop_index(op.f('ix_engagement_tenant_id'), table_name='engagement')
    op.drop_constraint('uq_engagement_external', 'engagement', type_='unique')
    op.create_unique_constraint(op.f('uq_engagement_external'), 'engagement', ['external_system', 'external_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('engagement', 'tenant_id')
    op.drop_index(op.f('ix_contact_tenant_id'), table_name='contact')
    op.drop_column('contact', 'tenant_id')
    op.drop_index(op.f('ix_compliance_status_tenant_id'), table_name='compliance_status')
    op.drop_column('compliance_status', 'tenant_id')
    op.drop_index(op.f('ix_account_tenant_id'), table_name='account')
    op.drop_constraint('uq_account_external', 'account', type_='unique')
    op.create_unique_constraint(op.f('uq_account_external'), 'account', ['external_system', 'external_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('account', 'tenant_id')
    # ### end Alembic commands ###
